name: bank-front-lab

services:
  bank-front:
    image:  "${BANK_FRONT_IMAGE:-bank-front:dev}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "${APP_VERSION:-0.0.0}"
        GIT_COMMIT: "${GIT_COMMIT_SHA:-unknown}"
        BUILD_DATE: "${BUILD_DATE:-unknown}"

    restart: unless-stopped

    ports:
      - "127.0.0.1:8086:8080"

    networks:
      - bank-net

networks:
  bank-net:
    external: true
    name: bank-net
