# Identification
sonar.projectKey=bank-front
sonar.projectName=Bank Front

# Sources
sonar.sources=src
sonar.sourceEncoding=UTF-8

# Tests
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts

# Coverage
sonar.javascript.lcov.reportPaths=coverage/bank-front/lcov.info
sonar.coverage.exclusions=src/main.ts,src/**/*.spec.ts

# Source control
sonar.scm.provider=git
